import { motion } from "framer-motion";
import { ArrowUpRight, Github, Layers3, ShieldCheck, Workflow } from "lucide-react";

const projects = [
  { title: "CreditHub", category: "Java · Spring Boot · Mensageria", description: "Plataforma de gestão de crédito com contratos REST, segurança JWT, PostgreSQL, Flyway e fluxos assíncronos. O foco está em consistência: Outbox, DLQ e consumidores idempotentes.", stack: ["Java 21", "Spring Boot", "RabbitMQ", "PostgreSQL", "Docker"], link: "https://github.com/Augustossn", icon: Workflow, tone: "cyan", featured: true },
  { title: "Automation Center", category: "Python · Django · Kafka", description: "Central para automatizar processos e integrações, combinando APIs REST, processamento assíncrono e uma interface React para acompanhar operações.", stack: ["Django", "Kafka", "Celery", "Redis", "Pytest"], link: "https://github.com/Augustossn", icon: Layers3, tone: "violet" },
  { title: "MaintainFlow", category: "C# · .NET · Clean Architecture", description: "Gestão de manutenções com domínio organizado, APIs em ASP.NET Core, EF Core, SQL Server, testes e mensagens assíncronas com RabbitMQ.", stack: [".NET 8", "EF Core", "SQL Server", "xUnit", "React"], link: "https://github.com/Augustossn", icon: ShieldCheck, tone: "amber" },
  { title: "SalvaDocs", category: "Angular · Node.js · TypeScript", description: "Aplicação full stack de gestão de documentos com componentes reutilizáveis, integração entre front-end e back-end e foco na experiência de uso.", stack: ["Angular", "Node.js", "TypeScript", "REST"], link: "https://github.com/Szervinsk/SalvaDocs", icon: Layers3, tone: "slate" },
];

export default function ProjectsSection() {
  return <section id="projetos" className="portfolio-projects py-20 md:py-28"><div className="mx-auto max-w-6xl px-5 md:px-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">Projetos selecionados</p><h2 className="section-title mt-4">Arquitetura, integração e produto em código.</h2><p className="section-copy">Projetos construídos para experimentar decisões reais de engenharia — não apenas reproduzir telas.</p></div><a className="link-arrow" href="https://github.com/Augustossn" target="_blank" rel="noreferrer">Explorar GitHub <Github size={17} /></a></div><div className="mt-12 grid gap-4 md:grid-cols-2">{projects.map((project, index) => { const Icon = project.icon; return <motion.article key={project.title} initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ delay: index * 0.06 }} whileHover={{ y: -6 }} className={`project-card project-${project.tone} ${project.featured ? "md:col-span-2" : ""}`}><div className="flex items-start justify-between gap-6"><div className="project-icon"><Icon size={21}/></div><span className="font-mono text-[10px] uppercase tracking-[.14em] text-muted-foreground">0{index + 1} / 04</span></div><div className={`mt-10 ${project.featured ? "md:grid md:grid-cols-[.7fr_1.3fr] md:gap-10" : ""}`}><div><p className="font-mono text-[11px] uppercase tracking-[.13em] text-accent">{project.category}</p><h3 className="mt-3 text-3xl font-bold tracking-[-.055em] md:text-4xl">{project.title}</h3></div><div><p className="mt-5 leading-7 text-muted-foreground md:mt-0">{project.description}</p><div className="mt-6 flex flex-wrap gap-2">{project.stack.map(item => <span key={item} className="tech-chip">{item}</span>)}</div><a href={project.link} target="_blank" rel="noreferrer" className="link-arrow mt-8">Ver repositório <ArrowUpRight size={17} /></a></div></div></motion.article>; })}</div></div></section>;
}
