import { ArrowUpRight, Github } from "lucide-react";

const projects = [
  { title: "CreditHub", purpose: "Plataforma de gestão de crédito", description: "Projeto Java que explora um fluxo de crédito com API REST, autenticação, banco relacional e processamento assíncrono.", details: ["Mensageria com RabbitMQ", "Padrão Outbox, DLQ e consumidores idempotentes", "Testes com Testcontainers e observabilidade com Prometheus/Grafana"], stack: ["Java 21", "Spring Boot", "PostgreSQL", "RabbitMQ", "Docker"], link: "https://github.com/Augustossn" },
  { title: "Automation Center", purpose: "Central de automação de processos", description: "Aplicação para organizar automações e integrações, com APIs, processamento assíncrono e acompanhamento das operações.", details: ["Serviços Python/Django", "Tarefas assíncronas e eventos", "Testes com Pytest, Docker e dados em PostgreSQL"], stack: ["Python", "Django", "Kafka", "Celery", "Redis"], link: "https://github.com/Augustossn" },
  { title: "MaintainFlow", purpose: "Gestão de manutenção", description: "Projeto full stack voltado à organização de manutenções, com domínio separado da infraestrutura e integrações por mensagem.", details: ["Clean Architecture com ASP.NET Core", "Persistência com EF Core e SQL Server", "Testes unitários, integração e interface React"], stack: ["C#", ".NET 8", "SQL Server", "React", "RabbitMQ"], link: "https://github.com/Augustossn" },
  { title: "SalvaDocs", purpose: "Gestão de documentos", description: "Aplicação full stack para organizar documentos e conectar uma interface baseada em componentes a serviços de back-end.", details: ["Componentes em Angular", "Serviços Node.js e APIs REST", "Integração entre front-end e back-end"], stack: ["Angular", "Node.js", "TypeScript", "REST"], link: "https://github.com/Szervinsk/SalvaDocs" },
];

export default function ProjectsSection() {
  return <section id="projetos" className="mx-auto max-w-6xl px-5 py-20 md:px-8 md:py-24"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">03 · Projetos</p><h2 className="section-title mt-4">Projetos técnicos</h2><p className="section-copy">Projetos usados para praticar decisões de arquitetura, integração, testes e operação de aplicações.</p></div><a className="link-arrow" href="https://github.com/Augustossn" target="_blank" rel="noreferrer">GitHub <Github size={17} /></a></div><div className="mt-10 grid gap-4 md:grid-cols-2">{projects.map((project, index) => <article key={project.title} className="border border-border bg-card p-6 md:p-7"><p className="font-mono text-xs text-accent">0{index + 1}</p><p className="mt-5 text-sm font-semibold text-muted-foreground">{project.purpose}</p><h3 className="mt-1 text-2xl font-bold tracking-[-.045em]">{project.title}</h3><p className="mt-5 leading-7 text-muted-foreground">{project.description}</p><ul className="mt-5 space-y-2 border-t border-border pt-5 text-sm leading-6 text-foreground">{project.details.map((detail) => <li key={detail} className="flex gap-2"><span className="text-accent">—</span><span>{detail}</span></li>)}</ul><div className="mt-6 flex flex-wrap gap-2">{project.stack.map((item) => <span key={item} className="tech-chip">{item}</span>)}</div><a href={project.link} target="_blank" rel="noreferrer" className="link-arrow mt-7">Ver repositório <ArrowUpRight size={17} /></a></article>)}</div></section>;
}
