const experience = [
  { period: "mar. 2026 — set. 2026", company: "Dali", role: "Desenvolvedor Full Stack · PJ", text: "Desenvolvimento de serviços Python/Django para uma plataforma no-code de automação. Atuei em APIs REST, regras condicionais, integrações, dashboards e fluxos para atendimento e vendas.", practices: "Trabalhei com Pytest, mocks, fixtures, Docker, GitHub Actions, pull requests e validação das entregas antes da publicação.", tags: ["Python", "Django", "APIs REST", "Pytest", "CI/CD"] },
  { period: "mar. 2025 — abr. 2026", company: "GIS Tecnologia", role: "Desenvolvedor Full Stack · PJ", text: "Evolução de APIs REST e regras de negócio em aplicações corporativas e financeiras. Integrei interfaces, serviços e bancos relacionais a partir das necessidades levantadas com o time.", practices: "Modelei dados, investiguei consultas SQL e participei de fluxos de versionamento e revisão de código.", tags: ["APIs REST", "SQL", "Integrações", "Git"] },
  { period: "set. 2025 — mar. 2026", company: "CAESB", role: "Estagiário em Análise e Desenvolvimento", text: "Desenvolvimento e manutenção de rotinas em Java, C\# e Python para automação de processos e relatórios internos.", practices: "Atuei com processamento de dados em SQL Server, manutenção de fluxos existentes e apoio às necessidades das equipes usuárias.", tags: ["Java", "C\#", "Python", "SQL Server"] },
];

export default function TimelineSection() {
  return <section id="experiencia" className="mx-auto max-w-6xl px-5 py-20 md:px-8 md:py-24"><div className="grid gap-10 md:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">01 · Experiência</p><h2 className="section-title mt-4">Experiência profissional</h2><p className="section-copy">Atuação em produtos corporativos, automação de processos, integrações e dados.</p></div><div className="border-t border-border">{experience.map((item) => <article key={item.company} className="grid gap-4 border-b border-border py-7 md:grid-cols-[10rem_1fr]"><p className="font-mono text-xs leading-5 text-muted-foreground">{item.period}</p><div><h3 className="text-lg font-bold">{item.company}</h3><p className="mt-1 text-sm font-semibold text-accent">{item.role}</p><p className="mt-4 leading-7 text-muted-foreground">{item.text}</p><p className="mt-3 text-sm leading-6 text-foreground">{item.practices}</p><div className="mt-4 flex flex-wrap gap-2">{item.tags.map((tag) => <span key={tag} className="tech-chip">{tag}</span>)}</div></div></article>)}</div></div></section>;
}
